<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="JyothiCyril" failures="1" tests="2" name="Functional Test - Amazon - DDT" time="12.658" errors="0" timestamp="2022-07-11T16:23:51 IST">
  <testcase classname="com.qa.testscripts.TC_Amazon_003" name="ItemsInCategoryList" time="1.319">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at com.qa.testscripts.TC_Amazon_003.ItemsInCategoryList(TC_Amazon_003.java:54)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- ItemsInCategoryList -->
  <testcase classname="com.qa.testscripts.TC_Amazon_003" name="validateMultipleItems" time="0.0">
    <skipped/>
  </testcase> <!-- validateMultipleItems -->
</testsuite> <!-- Functional Test - Amazon - DDT -->
